const titles = {
  mandatory: {
    database: [
      'Modelování databázových systémů, konceptuální modelování, datová analýza, funkční analýza, nástroje a modely',
      'Relační datový model, SQL, funkční závislosti, dekompozice a normální formy',
      'Transakce, zotavení, log, ACID, operace COMMIT a ROLLBACK, problémy souběhu, řízení souběhu: zamykání, úroveň izolace v SQL',
      'Procedurální rozšíření SQL, PL/SQL, T-SQL, triggery, funkce, procedury, kurzory, hromadné operace',
      'Základní fyzická implementace databázových systémů: tabulky a indexy; plán vykonávání dotazů',
      'Objektově‐relační datový model a XML datový model: principy, dotazovací jazyky',
      'Datová vrstva informačního systému, existující API, rámce a implementace, bezpečnost, objektově-relační mapování',
      'Distribuované SŘBD, fragmentace a replikace',
    ],
    math: [
      'Konečné automaty, regulární výrazy, regulární jazyky',
      'Bezkontextové gramatiky a jazyky, zásobníkové automaty, jejich vztah k bezkontextovým gramatikám',
      'Matematické modely algoritmů - Turingovy stroje a stroje RAM. Složitost algoritmu, asymptotické odhady, algoritmicky nerozhodnutelné problémy',
      'Třídy složitosti problémů. Třída PTIME a NPTIME, NP-úplné problémy. ',
      'Jazyk predikátové logiky prvního řádu. Práce s kvantifikátory a ekvivalentní transformace formulí',
      'Relace',
      'Algebra',
      'FCA – formální kontext, formální koncept, konceptuální svazy. ',
      'Asociační pravidla',
      'Metrické a topologické prostory – metriky a podobnosti',
      'Shlukování',
      'Náhodná veličina',
      'Vybraná rozdělení diskrétní a spojité náhodné veličiny - binomické, hypergeometrické, negativně binomické, Poissonovo, exponenciální, Weibullovo, normální rozdělení',
      'Popisná statistika. Číselné charakteristiky a vizualizace kategoriálních a kvantitativních proměnných',
      'Metody statistické indukce. Intervalové odhady. Princip testování hypotéz',
    ],
    network: [
      'Architektura univerzálních procesorů, principy urychlování činnosti procesorů',
      'Základní vlastnosti monolitických počítačů a jejich typické integrované periférie, možnosti použití',
      'Protokolová rodina TCP/IP',
      'Metody sdíleného přístupu ke společnému kanálu',
      'Problémy směrování v počítačových sítích. Adresování v IP, překlad adres (NAT). ',
      '?' 
    ],
    software_engineering: [
      'Softwarový proces. Jeho definice, modely a úrovně vyspělosti',
      'Vymezení fáze „sběr a analýza požadavků“. Diagramy UML využité v dané fázi',
      'Vymezení fáze „Návrh“. Diagramy UML využité v dané fázi. Návrhové vzory – členění, popis a příklady',
      'Objeketově orientované paradigma',
      'Mapování UML diagramů na zdrojový kód',
      'Správa paměti, virtuální stroj, podpora paralelního zpracování a vlákna',
      'Zpracování chyb v moderních programovacích jazycích, princip datových proudů, rozdíl mezi znakově a bytově orientovanými datovými proudy',
      'Jazyk UML',
    ],
  },
  optional: {
    data_analysis: [
      'Druhy dat, předzpracování dat, vlastnosti dat',
      'Hledání častých vzorů v datech',
      'Shlukovací metody',
      'Shlukování na základě hustoty, validace shluků, pokročilé metody shlukování (CLARANS,BIRCH, CURE)',
      'Rozhodovací stromy',
      'Pravděpodobnostní klasifikace',
      'Support Vector Machines',
      'Neuronové sítě',
      'Vyhodnocení klasifikačních algoritmů',
      'Regrese',
      'Typy sítí a jejich reprezentace, složitost operací, hybridní reprezentace',
      'Topologické vlastnosti sítí, charakteristické hodnoty a jejich distribuce, typy centralit',
      'Globální vlastnosti sítí a mocninný zákon.',
      'Modely sítí a jejich vlastnosti',
      'Komunity. Globální a lokální přístupy. Modularita.',
      'Jiné (pokročilé) modely sítí',
      'Odolnost sítí, šíření jevů v sítích',
      'Algoritmy pro pattern matching',
      'Dokumentografické informační systémy (DIS)',
      'Lineární algebra v DIS',
      'Vyhledávání na webu',
      'Paralelní výpočty a platformy: Flynnova taxonomie, SIMD, MIMD, SPMD. Datový a task paralelismus. Procesy a vlákna.',
      'Systémy se sdílenou a distribuovanou pamětí: komunikace mezi procesy (souběh, uváznutí, vzájemné vyloučení). Komunikace pomocí zasílání zpráv. OpenMP, MPI.',
      'Paralelní redukce a paralelní scan: principy fungování ve vybrané technologii a příklady užití.',
    ],
  },
}

export default titles
